apiVersion: skaffold/v2beta3
kind: Config
metadata:
  name: graph
deploy:
  statusCheckDeadlineSeconds: 300
  kustomize:
    paths:
    - k8s/overlays/development
profiles:
- name: production
  deploy:
    kustomize:
      paths:
      - k8s/overlays/production
