apiVersion: skaffold/v1
kind: Config
metadata:
  name: graph
deploy:
  statusCheckDeadlineSeconds: 300
  kustomize:
    path: k8s/overlays/development
profiles:
- name: production
  patches:
  - op: replace
    path: /deploy/kustomize/path
    value: k8s/overlays/production
