apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  labels:
    app: blackbox-exporter
spec:
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
      - name: blackbox-exporter
        image: prom/blackbox-exporter:v0.17.0
        resources:
          limits:
            memory: 64Mi
        ports:
        - containerPort: 9115
        livenessProbe:
          httpGet:
            port: 9115
            path: /metrics
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: 9115
            path: /metrics
          initialDelaySeconds: 10
          periodSeconds: 5
