apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  labels:
    app: blackbox-exporter
spec:
  selector:
    app: blackbox-exporter
  type: NodePort
  ports:
  - protocol: TCP
    port: 9115
    targetPort: 9115
