apiVersion: v1
kind: Service
metadata:
  name: grafana-image-renderer
  labels:
    app: grafana-image-renderer
spec:
  selector:
    app: grafana-image-renderer
  type: NodePort
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
