apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  selector:
    app: node-exporter
  clusterIP: None
  ports:
  - protocol: TCP
    port: 9100
    targetPort: 9100
